version: 2
jobs:
  build:
    branches:
      only:
        - master
        - feature/lyrics
    docker:
      - image: circleci/node:8
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "src/backend/yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless
      - save_cache:
          paths:
            - node_modules
            - src/backend/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "src/backend/yarn.lock" }}
      - deploy:
          name: Deploy
          command: ./.circleci/deploy.sh
