service: musish

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1

functions:
  landing:
    handler: landing/landing.landing
    events:
      - http:
          path: /
          method: get

  browse-overview:
    handler: browse/browse.overview
    events:
      - http:
          path: /browse/overview
          method: get

  browse-activity:
    handler: browse/activity.overview
    events:
      - http:
          path: /browse/activity
          method: get

  genius-song:
    handler: genius/song.details
    events:
      - http:
          path: /genius/song
          method: get
          cors: true

  genius-artist:
    handler: genius/artist.details
    events:
      - http:
          path: /genius/artist
          method: get
          cors: true


plugins:
  - serverless-offline
